### ISSUE TITLE
Running 'rails s' within the directory just gives a list of possible rails commands

### ISSUE THREAD

**Issue by ornerymoose** [iogbole/gentelella_on_rails#1]
Morning. According to your README this is not the intended behavior. Something I'm missing here?

**Comment by Katagena** [comment]
same problem here

**Comment by mt-davis** [comment]
Same issue as well.

**Comment by mt-davis** [comment]
I figured out the problem. The bin folder is missing. Run : 
"rake rails:update:bin" and that should fix the problem.

**Comment by mt-davis** [comment]
@ornerymoose and @Katagena are you experiencing similar issues?

**Comment by iogbole** [comment]
Cheers @mt-davis, closing this one out.
