### ISSUE TITLE
Javascript missing for views

### ISSUE THREAD

**Issue by kotowick** [iogbole/gentelella_on_rails#13]
Hello,

When trying to implement different features, like the form wizard, they don't work - meaning, it looks like the javascript for them is not loading. I copied and pasted the bottom part of the Javascript from the sample page (https://github.com/puikinsh/gentelella/blob/master/production/form_wizards.html) but it still doesn't work.

Here is an example of my local env, trying to implement the form wizard.

<img width="1200" alt="screen shot 2016-11-12 at 11 59 30 pm" src="https://cloud.githubusercontent.com/assets/1714316/20244381/18d47078-a934-11e6-8c0a-abe2f627beeb.png">

<img width="1434" alt="screen shot 2016-11-13 at 12 00 24 am" src="https://cloud.githubusercontent.com/assets/1714316/20244388/4c16cb16-a934-11e6-8f24-999a317a567a.png">

**Comment by iogbole** [comment]
Hey @kotowick , did you require the jquery.smartWizard.js file in your application.js file? You may need to copy it from the main genta repo if it's not in the genta on rails repo.

**Comment by broyal** [comment]
Hey @kotowick  - Did you ever resolve this? Im hitting a similar issue with the dynamic tables page and the bottom part of the javascript but can't seem to get it to work. See button table image below and how buttons are not rendering. 

![image](https://cloud.githubusercontent.com/assets/24907787/21631563/9de3523a-d20a-11e6-8b1c-446ad292eae6.png)
