### ISSUE TITLE
Heroku deploy

### ISSUE THREAD

**Issue by jtfl121** [iogbole/gentelella_on_rails#3]
Hi, I really like the template and I am thinking of adding it to an existing app I have but before I do that I tried pushing it up to heroku as is (pg gem added and rails_12factor) but Im getting a few errors and the the js does not seem to be working.

I've tried compiling both local and letting heroku compile and neither works for me. Any help would be awesome.

oh and here it is on heroku. http://genta.herokuapp.com/

Thanks

This is what I get from the inspector panel:

Failed to load resource: the server responded with a status of 404 (Not Found)
genta.herokuapp.com/:1 Failed to decode downloaded font: http://genta.herokuapp.com/fonts/glyphicons-halflings-regular.woff2
http://genta.herokuapp.com/fonts/fontawesome-webfont.woff?v=4.5.0 Failed to load resource: the server responded with a status of 404 (Not Found)
genta.herokuapp.com/:1 Failed to decode downloaded font: http://genta.herokuapp.com/fonts/glyphicons-halflings-regular.woff
http://genta.herokuapp.com/fonts/fontawesome-webfont.ttf?v=4.5.0 Failed to load resource: the server responded with a status of 404 (Not Found)
genta.herokuapp.com/:1 Failed to decode downloaded font: http://genta.herokuapp.com/fonts/glyphicons-halflings-regular.ttf

**Comment by iogbole** [comment]
@jtfl121 - I have not tried this on heroku yet. At first glance, you may want to try setting

> config.serve_static_files = true  

in your config/environments to see if it resolves it. Please let me know how it goes.

**Comment by jtfl121** [comment]
@iogbole  Yes I tried that as well but with no luck. I ended up just using a cdn for fontawesome and just using those fonts and nothing from glyphicons.

**Comment by edudepetris** [comment]
@jtfl121    The solution for me was use `scss/font-awesome`  
In **application.css** add `*= require fonts/scss/font-awesome`
In  **fonts/scss/_path.scss** I changed all `url` by `assets-url`([Assets pipeline helper](http://guides.rubyonrails.org/asset_pipeline.html#coding-links-to-assets))  

``` scss
  src: asset-url('#{$fa-font-path}/fontawesome-webfont.eot?v=#{$fa-version}');
  src: asset-url('#{$fa-font-path}/fontawesome-webfont.eot?#iefix&v=#{$fa-version}') format('embedded-opentype'),
    asset-url('#{$fa-font-path}/fontawesome-webfont.woff2?v=#{$fa-version}') format('woff2'),
    asset-url('#{$fa-font-path}/fontawesome-webfont.woff?v=#{$fa-version}') format('woff'),
    asset-url('#{$fa-font-path}/fontawesome-webfont.ttf?v=#{$fa-version}') format('truetype'),
    asset-url('#{$fa-font-path}/fontawesome-webfont.svg?v=#{$fa-version}#fontawesomeregular') format('svg');
```

Then  I had to fit the **path** of fonts in **fonts/scss/_variables.scss** I changed the path by `"fonts/fonts"`

``` scss
$fa-font-path:        "fonts/fonts" !default;
```

**Comment by nkrus** [comment]
I ran into the same problem here, with missing **fonts** and **javascript** not working in production mode on Heroku. After several hours i found the solution:

**To fix fonts:**
It's simple if using [font-awesome-rails](https://github.com/bokmann/font-awesome-rails) gem. Just add to your **Gemfile**:
`gem "font-awesome-rails"`

Then in your **application.css**  remove line:
`*= require fonts/css/font-awesome.min.css`
and put this one instead:
`*= require font-awesome.css.erb`
_You can also remove your old font-awesome files from **vendor/.../fonts** folder._

**To fix javascript:**
It seems something wrong with one of the scripts required in **application.js**, called `gauge_demo.js` and Asset Pipeline can't handle with it. 
Everything works on Heroku after i removed this line:
`//= require js/gauge/gauge_demo.js`

_You can check this work before push on Heroku, by changing in your **config/development.rb**_
from:
`config.assets.debug = true`
to:
`config.assets.debug = false`

P.S don't forget to recompile assets, if you push into existing app on Heroku.
Remove old **public/assets** folder and run:
`rake assets:precompile`

**Comment by iogbole** [comment]
@jtfl121 and all who had this issue, this pull request resolves the assets, glyps, fonts & js issues in heroku and in production mode - https://github.com/iogbole/gentelella_on_rails/pull/10.
